# Generated by Django 4.0 on 2021-12-28 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0003_remove_drone_medication'),
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='drone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drone_load', to='drone.drone'),
        ),
    ]
