# Generated by Django 4.0 on 2021-12-28 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
        ('drone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medication_load', to='medication.medication'),
        ),
    ]
