# Generated by Django 4.0 on 2021-12-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0002_drone_medication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='medication',
        ),
    ]
